include ../../Library/Config.mk
RUDIX_UNIVERSAL=no
include ../../Library/Rudix.mk
include ../../Library/GNUFormula.mk

Title=		GNU MP
Name=		gmp
Version=	5.0.5
Revision=	0
URL=		http://ftp.gnu.org/gnu/gmp/
Source=		$(Name)-$(Version).tar.bz2

ReadMeFile=	$(SourceDir)/README
LicenseFile=	$(SourceDir)/COPYING

#GnuConfigureExtra += --enable-fat=yes
GnuConfigureExtra += --enable-cxx

ifdef ONLY_STATIC_LIBS
GnuConfigureExtra += --enable-static --disable-shared
endif
